/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Lp04VipRouteImport } from './routes/lp-04-vip'
import { Route as Lp04RouteImport } from './routes/lp-04'
import { Route as Lp03RouteImport } from './routes/lp-03'
import { Route as Lp02RouteImport } from './routes/lp-02'
import { Route as Lp01RouteImport } from './routes/lp-01'
import { Route as CartaVipRouteImport } from './routes/carta-vip'
import { Route as IndexRouteImport } from './routes/index'

const Lp04VipRoute = Lp04VipRouteImport.update({
  id: '/lp-04-vip',
  path: '/lp-04-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp04Route = Lp04RouteImport.update({
  id: '/lp-04',
  path: '/lp-04',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp03Route = Lp03RouteImport.update({
  id: '/lp-03',
  path: '/lp-03',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp02Route = Lp02RouteImport.update({
  id: '/lp-02',
  path: '/lp-02',
  getParentRoute: () => rootRouteImport,
} as any)
const Lp01Route = Lp01RouteImport.update({
  id: '/lp-01',
  path: '/lp-01',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaVipRoute = CartaVipRouteImport.update({
  id: '/carta-vip',
  path: '/carta-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carta-vip': typeof CartaVipRoute
  '/lp-01': typeof Lp01Route
  '/lp-02': typeof Lp02Route
  '/lp-03': typeof Lp03Route
  '/lp-04': typeof Lp04Route
  '/lp-04-vip': typeof Lp04VipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carta-vip': typeof CartaVipRoute
  '/lp-01': typeof Lp01Route
  '/lp-02': typeof Lp02Route
  '/lp-03': typeof Lp03Route
  '/lp-04': typeof Lp04Route
  '/lp-04-vip': typeof Lp04VipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carta-vip': typeof CartaVipRoute
  '/lp-01': typeof Lp01Route
  '/lp-02': typeof Lp02Route
  '/lp-03': typeof Lp03Route
  '/lp-04': typeof Lp04Route
  '/lp-04-vip': typeof Lp04VipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carta-vip'
    | '/lp-01'
    | '/lp-02'
    | '/lp-03'
    | '/lp-04'
    | '/lp-04-vip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carta-vip'
    | '/lp-01'
    | '/lp-02'
    | '/lp-03'
    | '/lp-04'
    | '/lp-04-vip'
  id:
    | '__root__'
    | '/'
    | '/carta-vip'
    | '/lp-01'
    | '/lp-02'
    | '/lp-03'
    | '/lp-04'
    | '/lp-04-vip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartaVipRoute: typeof CartaVipRoute
  Lp01Route: typeof Lp01Route
  Lp02Route: typeof Lp02Route
  Lp03Route: typeof Lp03Route
  Lp04Route: typeof Lp04Route
  Lp04VipRoute: typeof Lp04VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lp-04-vip': {
      id: '/lp-04-vip'
      path: '/lp-04-vip'
      fullPath: '/lp-04-vip'
      preLoaderRoute: typeof Lp04VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-04': {
      id: '/lp-04'
      path: '/lp-04'
      fullPath: '/lp-04'
      preLoaderRoute: typeof Lp04RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-03': {
      id: '/lp-03'
      path: '/lp-03'
      fullPath: '/lp-03'
      preLoaderRoute: typeof Lp03RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-02': {
      id: '/lp-02'
      path: '/lp-02'
      fullPath: '/lp-02'
      preLoaderRoute: typeof Lp02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-01': {
      id: '/lp-01'
      path: '/lp-01'
      fullPath: '/lp-01'
      preLoaderRoute: typeof Lp01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta-vip': {
      id: '/carta-vip'
      path: '/carta-vip'
      fullPath: '/carta-vip'
      preLoaderRoute: typeof CartaVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartaVipRoute: CartaVipRoute,
  Lp01Route: Lp01Route,
  Lp02Route: Lp02Route,
  Lp03Route: Lp03Route,
  Lp04Route: Lp04Route,
  Lp04VipRoute: Lp04VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
